services:
  macos:
    container_name: macos
    image: ghcr.io/dockur/macos
    environment:
      RAM_SIZE: "34GB"
      DISK_SIZE: "100TB"
      CPU_CORES: "5"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    volumes:
      - ./macos:/storage
    restart: on-failure
    stop_grace_period: 2m
